In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [2]:
df = pd.read_csv("all_seasons.csv")   # Replace with your filename

In [3]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

df.head()

Rows: 12844
Columns: 22

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,42,64,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,34,4,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,12,41,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,7,64,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,22,52,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97

In [4]:
df.columns.tolist()

['Unnamed: 0',
 'player_name',
 'team_abbreviation',
 'age',
 'player_height',
 'player_weight',
 'college',
 'country',
 'draft_year',
 'draft_round',
 'draft_number',
 'gp',
 'pts',
 'reb',
 'ast',
 'net_rating',
 'oreb_pct',
 'dreb_pct',
 'usg_pct',
 'ts_pct',
 'ast_pct',
 'season']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12844 entries, 0 to 12843
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         12844 non-null  int64
 1   player_name        12844 non-null  object
 2   team_abbreviation  12844 non-null  object
 3   age                12844 non-null  float64
 4   player_height      12844 non-null  float64
 5   player_weight      12844 non-null  float64
 6   college            10990 non-null  object
 7   country            12844 non-null  object
 8   draft_year         12844 non-null  object
 9   draft_round        12844 non-null  object
 10  draft_number       12844 non-null  object
 11  gp                 12844 non-null  int64
 12  pts                12844 non-null  float64
 13  reb                12844 non-null  float64
 14  ast                12844 non-null  float64
 15  net_rating         12844 non-null  float64
 16  oreb_pct           12844 non-null  float64
 17  dreb_pct           12844 non-null  float64
 18  usg_pct            12844 non-null  float64
 19  ts_pct             12844 non-null  float64
 20  ast_pct            12844 non-null  float64
 21  season             12844 non-null  object
dtypes: float64(12), int64(2), object(8)
memory usage: 2.2+ MB

In [6]:
df.describe()

,Unnamed: 0,age,player_height,player_weight,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct
count,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000
mean,6421.500000,27.045313,200.555097,100.263279,51.154158,8.212582,3.558486,1.824681,-2.226339,0.054073,0.140646,0.184641,0.513138,0.131595
std,3707.887763,4.339211,9.111090,12.426628,25.084904,6.016573,2.477885,1.800840,12.665124,0.043335,0.062513,0.053545,0.101724,0.094172
min,0.000000,18.000000,160.020000,60.327736,1.000000,0.000000,0.000000,0.000000,-250.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3210.750000,24.000000,193.040000,90.718400,31.000000,3.600000,1.800000,0.600000,-6.400000,0.021000,0.096000,0.149000,0.482000,0.066000
50%,6421.500000,26.000000,200.660000,99.790240,57.000000,6.700000,3.000000,1.200000,-1.300000,0.040000,0.130500,0.181000,0.525000,0.103000
75%,9632.250000,30.000000,208.280000,108.862080,73.000000,11.500000,4.700000,2.400000,3.200000,0.083000,0.179000,0.217000,0.563000,0.179000
max,12843.000000,44.000000,231.140000,163.293120,85.000000,36.100000,16.300000,11.700000,300.000000,1.000000,1.000000,1.000000,1.500000,1.000000

In [7]:
df.describe(include="all")

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
count,12844.00,12844,12844,12844.000000,12844.000000,12844.000000,10990,12844,12844,12844,12844,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844.000000,12844
unique,NaN,2551,36,NaN,NaN,NaN,356,82,48,9,76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27
top,NaN,Vince Carter,CLE,NaN,NaN,NaN,Kentucky,USA,Undrafted,1,Undrafted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-22
freq,NaN,22,450,NaN,NaN,NaN,447,10721,2358,7351,2414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605
mean,6421.50,NaN,NaN,27.045313,200.555097,100.263279,NaN,NaN,NaN,NaN,NaN,51.154158,8.212582,3.558486,1.824681,-2.226339,0.054073,0.140646,0.184641,0.513138,0.131595,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
min,0.00,NaN,NaN,18.000000,160.020000,60.327736,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,-250.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,3210.75,NaN,NaN,24.000000,193.040000,90.718400,NaN,NaN,NaN,NaN,NaN,31.000000,3.600000,1.800000,0.600000,-6.400000,0.021000,0.096000,0.149000,0.482000,0.066000,NaN
50%,6421.50,NaN,NaN,26.000000,200.660000,99.790240,NaN,NaN,NaN,NaN,NaN,57.000000,6.700000,3.000000,1.200000,-1.300000,0.040000,0.130500,0.181000,0.525000,0.103000,NaN
75%,9632.25,NaN,NaN,30.000000,208.280000,108.862080,NaN,NaN,NaN,NaN,NaN,73.000000,11.500000,4.700000,2.400000,3.200000,0.083000,0.179000,0.217000,0.563000,0.179000,NaN
max,12843.00,NaN,NaN,44.000000,231.140000,163.293120,NaN,NaN,NaN,NaN,NaN,85.000000,36.100000,16.300000,11.700000,300.000000,1.000000,1.000000,1.000000,1.500000,1.000000,NaN

In [8]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().mean() * 100).round(2)
})

missing.sort_values("Missing Values", ascending=False)

                   Missing Values  Percentage
college                      1854       14.43
Unnamed: 0                      0        0.00
pts                             0        0.00
ast_pct                         0        0.00
ts_pct                          0        0.00
...                           ...         ...
player_weight                   0        0.00
player_height                   0        0.00
age                             0        0.00
team_abbreviation               0        0.00
season                          0        0.00

[22 rows x 2 columns]

In [9]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows: {duplicates}")

Duplicate Rows: 0

In [10]:
df.dtypes

Unnamed: 0             int64
player_name           object
team_abbreviation     object
age                  float64
player_height        float64
                      ...
dreb_pct             float64
usg_pct              float64
ts_pct               float64
ast_pct              float64
season                object
Length: 22, dtype: object

In [11]:
unique_values = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique_values.sort_values("Unique Values")

                   Unique Values
draft_round                    9
season                        27
age                           27
player_height                 30
team_abbreviation             36
...                          ...
ast_pct                      483
ts_pct                       563
net_rating                   772
player_name                 2551
Unnamed: 0                 12844

[22 rows x 1 columns]

In [12]:
df.sample(10, random_state=42)

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
7207,7207,Tyrus Thomas,CHA,26.0,208.28,102.058200,Louisiana State,USA,2006,1,4,26,4.8,2.3,0.7,-12.1,0.048,0.143,0.213,0.418,0.094,2012-13
11627,11627,Keljin Blevins,POR,25.0,193.04,90.718400,Montana State,USA,2019,Undrafted,Undrafted,17,0.7,0.6,0.2,-22.2,0.031,0.071,0.126,0.300,0.083,2020-21
8348,8348,Zaza Pachulia,MIL,31.0,210.82,122.469840,NaN,Georgia,2003,2,42,73,8.3,6.8,2.4,6.9,0.133,0.206,0.189,0.506,0.155,2014-15
9255,9255,Patrick Beverley,HOU,28.0,185.42,83.914520,Arkansas,USA,2009,2,42,67,9.5,5.9,4.2,7.3,0.050,0.159,0.141,0.546,0.184,2016-17
9909,9909,Allen Crabbe,BKN,26.0,198.12,97.522280,California,USA,2013,2,31,75,13.2,4.3,1.6,-1.9,0.012,0.130,0.183,0.558,0.082,2017-18
4850,4850,John Lucas III,HOU,24.0,180.34,74.842680,Oklahoma State,USA,Undrafted,Undrafted,Undrafted,47,3.3,0.8,0.7,-1.5,0.026,0.089,0.223,0.468,0.167,2006-07
4064,4064,Ime Udoka,NYK,28.0,195.58,99.790240,Portland State,USA,Undrafted,Undrafted,Undrafted,8,2.8,2.1,0.8,-4.2,0.035,0.152,0.121,0.413,0.082,2005-06
5304,5304,Mike James,NOH,33.0,187.96,85.275296,Duquesne,USA,Undrafted,Undrafted,Undrafted,54,5.0,1.3,1.1,-2.4,0.022,0.089,0.222,0.437,0.142,2007-08
1983,1983,Anthony Carter,MIA,26.0,185.42,86.182480,Hawaii,USA,Undrafted,Undrafted,Undrafted,72,6.4,2.5,3.7,2.6,0.034,0.094,0.190,0.439,0.305,2000-01
12789,12789,Jaden McDaniels,MIN,22.0,205.74,83.914520,Washington,USA,2020,1,28,79,12.1,3.9,1.9,2.0,0.039,0.086,0.156,0.611,0.082,2022-23